In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

df = pd.read_csv('player_box_scores.csv')

In [2]:
def create_target(row):
    row = row.sort_values(by='Date')
    row['target'] = row['PTS'].shift(-1)
    return row

grouped_df = df.groupby('Player ID', group_keys=False).apply(create_target)

/var/folders/l1/18hvv2_s6b9542kc8v68nx8r0000gn/T/ipykernel_90240/97184926.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_df = df.groupby('Player ID', group_keys=False).apply(create_target)

In [3]:
grouped_df

,Unnamed: 0,Player ID,Name,G,Date,Age,Tm,Away?,Opp,Result,GS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,target
87175,87175,abdelal01,Alaa Abdelnaby,1.0,1990-11-02,22.358904,POR,False,HOU,1,0.0,5.000000,0,1.0,0.000,0,0.0,NaN,0,0,NaN,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0,1.0,NaN,0.0
87176,87176,abdelal01,Alaa Abdelnaby,2.0,1990-11-06,22.369863,POR,True,LAL,2,0.0,4.000000,0,0.0,NaN,0,0.0,NaN,0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0,-2.2,NaN,4.0
87177,87177,abdelal01,Alaa Abdelnaby,3.0,1990-11-11,22.383562,POR,False,LAC,31,0.0,8.000000,2,4.0,0.500,0,0.0,NaN,0,0,NaN,1.0,3.0,4.0,1.0,0.0,0.0,0.0,1.0,4,3.9,NaN,0.0
87178,87178,abdelal01,Alaa Abdelnaby,4.0,1990-11-13,22.389041,POR,False,DEN,26,0.0,3.000000,0,2.0,0.000,0,0.0,NaN,0,0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0,-2.1,NaN,1.0
87179,87179,abdelal01,Alaa Abdelnaby,5.0,1990-11-15,22.394521,POR,False,NYK,16,0.0,6.000000,0,2.0,0.000,0,0.0,NaN,1,2,0.5,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,-0.1,NaN,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
904752,904752,zubaciv01,Ivica Zubac,64.0,2024-04-04,27.046575,LAC,False,DEN,2,1.0,34.816667,4,11.0,0.364,0,0.0,NaN,6,6,1.0,1.0,14.0,15.0,1.0,1.0,0.0,0.0,4.0,14,12.9,-5.0,12.0
904753,904753,zubaciv01,Ivica Zubac,65.0,2024-04-05,27.049315,LAC,False,UTA,29,1.0,23.950000,5,6.0,0.833,0,0.0,NaN,2,2,1.0,2.0,8.0,10.0,2.0,1.0,3.0,0.0,4.0,12,16.5,15.0,14.0
904754,904754,zubaciv01,Ivica Zubac,66.0,2024-04-07,27.054795,LAC,False,CLE,2,1.0,27.383333,7,10.0,0.700,0,0.0,NaN,0,0,NaN,4.0,7.0,11.0,1.0,0.0,0.0,3.0,1.0,14,12.0,-10.0,17.0
904755,904755,zubaciv01,Ivica Zubac,67.0,2024-04-09,27.060274,LAC,True,PHO,13,1.0,27.933333,8,13.0,0.615,0,0.0,NaN,1,1,1.0,2.0,11.0,13.0,2.0,0.0,2.0,3.0,0.0,17,15.6,17.0,10.0
904756,904756,zubaciv01,Ivica Zubac,68.0,2024-04-12,27.068493,LAC,False,UTA,-1,1.0,10.316667,5,6.0,0.833,0,0.0,NaN,0,0,NaN,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,10,9.9,8.0,NaN

In [4]:
nulls = pd.isnull(df)
nulls = nulls.sum()
nulls[nulls > 0]

GS           1
FGA          5
FG%      49956
3PA       4151
3P%     525378
FT%     401112
ORB      22442
DRB      22442
TRB          1
AST          3
STL      12465
BLK       5075
TOV      13417
PF          16
GmSc     26544
+/-     351260
dtype: int64

In [5]:
filtered_df = grouped_df[grouped_df['Date'] >= '1996-09-01']

In [6]:
nulls = pd.isnull(filtered_df)
nulls = nulls.sum()
nulls = nulls[nulls > 0]

In [7]:
filtered_df[filtered_df['+/-'].isnull()]

,Unnamed: 0,Player ID,Name,G,Date,Age,Tm,Away?,Opp,Result,GS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,target
869434,869434,achiupr01,Precious Achiuwa,50.0,2023-03-31,23.528767,TOR,True,PHI,-7,0.0,7.133333,2,5.0,0.400,0,2.0,0.000,0,0,NaN,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,4,2.7,NaN,8.0
151992,151992,aldamsa01,Santi Aldama,74.0,2023-03-31,22.219178,MEM,False,LAC,14,0.0,16.333333,4,9.0,0.444,0,1.0,0.000,5,5,1.0,2.0,6.0,8.0,0.0,0.0,1.0,2.0,2.0,13,9.4,NaN,3.0
965746,965746,alexani01,Nickeil Alexander-Walker,55.0,2023-03-31,24.575342,MIN,False,LAL,-12,0.0,3.900000,0,1.0,0.000,0,1.0,0.000,0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,-0.7,NaN,7.0
32725,32725,alexavi01,Victor Alexander,11.0,2002-03-26,32.567123,DET,True,IND,19,0.0,1.000000,0,0.0,NaN,0,0.0,NaN,0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,NaN,3.0
190040,190040,anderky01,Kyle Anderson,65.0,2023-03-31,29.526027,MIN,False,LAL,-12,0.0,31.483333,8,11.0,0.727,1,2.0,0.500,0,0,NaN,2.0,2.0,4.0,6.0,2.0,3.0,1.0,0.0,17,21.8,NaN,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446475,446475,wisemja01,James Wiseman,40.0,2023-03-31,22.000000,DET,True,HOU,-6,1.0,23.500000,4,10.0,0.400,0,2.0,0.000,0,0,NaN,1.0,3.0,4.0,1.0,0.0,3.0,0.0,6.0,8,4.6,NaN,12.0
222073,222073,wrighde01,Delon Wright,48.0,2023-03-31,30.928767,WAS,False,ORL,-7,1.0,32.083333,8,15.0,0.533,2,6.0,0.333,3,3,1.0,3.0,6.0,9.0,4.0,1.0,0.0,0.0,2.0,21,20.6,NaN,8.0
411852,411852,zelleco01,Cody Zeller,23.0,2023-12-26,31.224658,NOP,False,MEM,-1,0.0,0.000000,0,0.0,NaN,0,0.0,NaN,0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,NaN,4.0
638919,638919,zhizhwa01,Wang Zhizhi,1.0,2002-11-01,25.317808,LAC,False,LAL,-15,0.0,1.100000,0,0.0,NaN,0,0.0,NaN,0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,NaN,5.0
712130,712130,zubaciv01,Ivica Zubac,72.0,2023-03-31,26.035616,LAC,True,MEM,-14,1.0,25.633333,6,10.0,0.600,0,0.0,NaN,3,5,0.6,5.0,10.0,15.0,0.0,2.0,1.0,2.0,2.0,15,16.0,NaN,15.0

In [8]:
#Since +/- is important, we will impute the values with a Linear Regression model
from sklearn.linear_model import LinearRegression

# Select relevant features for prediction
features = ['Result', 'GS', 'MP', 'FG', 'FGA', '3P', '3PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'GmSc']

# Separate rows with and without missing `+/-`
df_not_null = filtered_df[filtered_df['+/-'].notna()]
df_null = filtered_df[filtered_df['+/-'].isna()]

# Train a model
model = LinearRegression()
model.fit(df_not_null[features], df_not_null['+/-'])

# Predict missing values
filtered_df.loc[filtered_df['+/-'].isna(), '+/-'] = model.predict(df_null[features])

/Users/davidmorin/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [9]:
filtered_df.loc[:, 'target'] = filtered_df['target'].fillna(-1)

In [10]:
nulls = pd.isnull(filtered_df)
nulls = nulls.sum()
nulls = nulls[nulls > 0]
nulls

FG%     34501
3P%    272841
FT%    280435
dtype: int64

In [11]:
valid_cols = filtered_df.columns[~filtered_df.columns.isin(nulls.index)]

In [12]:
valid_cols

Index(['Unnamed: 0', 'Player ID', 'Name', 'G', 'Date', 'Age', 'Tm', 'Away?',
       'Opp', 'Result', 'GS', 'MP', 'FG', 'FGA', '3P', '3PA', 'FT', 'FTA',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'GmSc',
       '+/-', 'target'],
      dtype='object')

In [13]:
predictor_df = filtered_df[valid_cols].copy()
predictor_df['Away?'] = predictor_df['Away?'].astype(int)
predictor_df['Season'] = pd.to_datetime(predictor_df['Date']).dt.year
predictor_df = predictor_df.drop('Unnamed: 0', axis=1)

In [14]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector


model = LinearRegression()
split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(model, n_features_to_select=15, direction='forward', cv=split)

In [15]:
removed_columns = ['Player ID', 'Date', 'Name', 'Tm', 'Opp', 'target', 'Season' ]

In [16]:
selected_columns = predictor_df.columns[~predictor_df.columns.isin(removed_columns)]

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
predictor_df[selected_columns] = scaler.fit_transform(predictor_df[selected_columns])

In [18]:
sfs.fit(predictor_df[selected_columns], predictor_df['target'])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=LinearRegression(),
                          n_features_to_select=15)

In [19]:
predictors = list(selected_columns[sfs.get_support()])

In [20]:
predictors

['G',
 'Age',
 'Result',
 'GS',
 'FGA',
 'FT',
 'FTA',
 'ORB',
 'TRB',
 'AST',
 'STL',
 'TOV',
 'PF',
 'GmSc',
 '+/-']

In [21]:
#We can not do typical cross validation because we have time series data, so we need to right
#a function to ensure that training data is from chronologically earlier than test data
def backtest(data, model, predictors, start=4, step=1):
    all_predictions = [] #List of DF
    seasons = sorted(data['Season'].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        train = data[data['Season'] < season]
        test = data[data['Season'] == season]
        
        model.fit(train[predictors], train['target'])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        
        combined = pd.concat([test['target'], preds], axis=1)
        combined.columns = ['actual', 'prediction']
        
        all_predictions.append(combined)
    
    return pd.concat(all_predictions)

In [22]:
predictions = backtest(predictor_df, model, predictors)

In [23]:
predictions

        actual  prediction
258574     2.0    2.378522
258575     0.0    2.122747
258576     0.0    4.425296
258577     4.0    2.280837
258578     2.0    4.974720
...        ...         ...
904752    12.0   15.558197
904753    14.0   10.035055
904754    17.0   12.156282
904755    10.0   15.447381
904756    -1.0    8.202997

[609582 rows x 2 columns]

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

predictions = predictions[predictions['actual'] != -1]

mae = mean_absolute_error(predictions['actual'], predictions['prediction'])
mse = mean_squared_error(predictions['actual'], predictions['prediction'])
rmse = mean_squared_error(predictions['actual'], predictions['prediction'], squared=False)
r2 = r2_score(predictions['actual'], predictions['prediction'])

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R-squared: {r2}")

MAE: 4.725919107867636
MSE: 38.08965997054379
RMSE: 6.171682102194166
R-squared: 0.4358510619636984

In [25]:
predictor_df

,Player ID,Name,G,Date,Age,Tm,Away?,Opp,Result,GS,MP,FG,FGA,3P,3PA,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,target,Season
154175,abdulma02,Mahmoud Abdul-Rauf,0.000000,1996-11-01,0.362176,SAC,1.0,HOU,0.424658,1.0,0.467460,0.250000,0.26,0.071429,0.083333,0.076923,0.051282,0.000000,0.08,0.060606,0.20,0.090909,0.076923,0.142857,0.285714,0.209877,0.335535,0.443478,2.0,1996
154176,abdulma02,Mahmoud Abdul-Rauf,0.011905,1996-11-02,0.362279,SAC,1.0,DAL,0.589041,1.0,0.393651,0.035714,0.14,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.08,0.090909,0.000000,0.000000,0.285714,0.024691,0.142668,0.495652,16.0,1996
154177,abdulma02,Mahmoud Abdul-Rauf,0.023810,1996-11-05,0.362588,SAC,0.0,HOU,0.349315,1.0,0.476190,0.285714,0.26,0.000000,0.000000,0.000000,0.025641,0.000000,0.08,0.060606,0.12,0.000000,0.000000,0.214286,0.285714,0.197531,0.268164,0.365217,0.0,1996
154178,abdulma02,Mahmoud Abdul-Rauf,0.035714,1996-11-07,0.362794,SAC,0.0,ATL,0.472603,1.0,0.531217,0.000000,0.12,0.000000,0.041667,0.000000,0.000000,0.000000,0.04,0.030303,0.28,0.000000,0.000000,0.142857,0.428571,0.000000,0.125495,0.521739,7.0,1996
154179,abdulma02,Mahmoud Abdul-Rauf,0.047619,1996-11-11,0.363206,SAC,0.0,SEA,0.390411,1.0,0.470370,0.107143,0.16,0.000000,0.000000,0.038462,0.025641,0.000000,0.04,0.030303,0.16,0.181818,0.000000,0.071429,0.285714,0.086420,0.232497,0.373913,11.0,1996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
904752,zubaciv01,Ivica Zubac,0.750000,2024-04-04,0.339514,LAC,0.0,DEN,0.513699,1.0,0.552646,0.142857,0.22,0.000000,0.000000,0.230769,0.153846,0.055556,0.56,0.454545,0.04,0.090909,0.000000,0.000000,0.571429,0.172840,0.324967,0.460870,12.0,2024
904753,zubaciv01,Ivica Zubac,0.761905,2024-04-05,0.339617,LAC,0.0,UTA,0.698630,1.0,0.380159,0.178571,0.12,0.000000,0.000000,0.076923,0.051282,0.111111,0.32,0.303030,0.08,0.090909,0.230769,0.000000,0.571429,0.148148,0.372523,0.634783,14.0,2024
904754,zubaciv01,Ivica Zubac,0.773810,2024-04-07,0.339823,LAC,0.0,CLE,0.513699,1.0,0.434656,0.250000,0.20,0.000000,0.000000,0.000000,0.000000,0.222222,0.28,0.333333,0.04,0.000000,0.000000,0.214286,0.142857,0.172840,0.313078,0.417391,17.0,2024
904755,zubaciv01,Ivica Zubac,0.785714,2024-04-09,0.340029,LAC,1.0,PHO,0.589041,1.0,0.443386,0.285714,0.26,0.000000,0.000000,0.038462,0.025641,0.111111,0.44,0.393939,0.08,0.000000,0.153846,0.214286,0.000000,0.209877,0.360634,0.652174,10.0,2024
904756,zubaciv01,Ivica Zubac,0.797619,2024-04-12,0.340338,LAC,0.0,UTA,0.493151,1.0,0.163757,0.178571,0.12,0.000000,0.000000,0.000000,0.000000,0.111111,0.00,0.060606,0.00,0.000000,0.076923,0.000000,0.000000,0.123457,0.285337,0.573913,-1.0,2024

In [26]:
predictor_df_rolling = predictor_df[list(selected_columns) + ['Player ID', 'Season']]

In [27]:
def find_player_averages(player):
    rolling = player[selected_columns].rolling(10).mean()
    non_numeric_columns = player[['Player ID', 'Season']]
    result = pd.concat([non_numeric_columns, rolling], axis=1)
    return result

predictor_df_rolling = predictor_df_rolling.groupby(['Player ID', 'Season'], group_keys=False).apply(find_player_averages)

/var/folders/l1/18hvv2_s6b9542kc8v68nx8r0000gn/T/ipykernel_90240/3051645565.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  predictor_df_rolling = predictor_df_rolling.groupby(['Player ID', 'Season'], group_keys=False).apply(find_player_averages)

In [28]:
predictor_df_rolling

,Player ID,Season,G,Age,Away?,Result,GS,MP,FG,FGA,3P,3PA,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
154175,abdulma02,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154176,abdulma02,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154177,abdulma02,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154178,abdulma02,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154179,abdulma02,1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
904752,zubaciv01,2024,0.696429,0.338628,0.6,0.484247,1.0,0.439815,0.171429,0.160,0.0,0.0,0.096154,0.074359,0.155556,0.268,0.287879,0.056,0.072727,0.107692,0.057143,0.385714,0.149383,0.327741,0.483478
904753,zubaciv01,2024,0.708333,0.338813,0.6,0.515753,1.0,0.440926,0.185714,0.170,0.0,0.0,0.088462,0.069231,0.144444,0.292,0.300000,0.060,0.081818,0.123077,0.050000,0.414286,0.156790,0.338045,0.513913
904754,zubaciv01,2024,0.720238,0.338999,0.5,0.508219,1.0,0.446376,0.185714,0.172,0.0,0.0,0.088462,0.069231,0.144444,0.300,0.306061,0.056,0.045455,0.107692,0.064286,0.400000,0.156790,0.327741,0.494783
904755,zubaciv01,2024,0.732143,0.339184,0.5,0.511644,1.0,0.462249,0.203571,0.192,0.0,0.0,0.092308,0.071795,0.150000,0.316,0.321212,0.064,0.036364,0.115385,0.064286,0.328571,0.170370,0.342272,0.497391
904756,zubaciv01,2024,0.744048,0.339380,0.5,0.520548,1.0,0.432275,0.203571,0.186,0.0,0.0,0.080769,0.061538,0.144444,0.288,0.296970,0.056,0.036364,0.092308,0.064286,0.328571,0.166667,0.333289,0.500000

In [29]:
rolling_columns = [f"{col}_10" for col in predictor_df_rolling.columns]
predictor_df_rolling.columns = rolling_columns

predictor_df = pd.concat([predictor_df, predictor_df_rolling], axis=1)
predictor_df.dropna(inplace=True)
predictor_df

,Player ID,Name,G,Date,Age,Tm,Away?,Opp,Result,GS,MP,FG,FGA,3P,3PA,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,target,Season,Player ID_10,Season_10,G_10,Age_10,Away?_10,Result_10,GS_10,MP_10,FG_10,FGA_10,3P_10,3PA_10,FT_10,FTA_10,ORB_10,DRB_10,TRB_10,AST_10,STL_10,BLK_10,TOV_10,PF_10,PTS_10,GmSc_10,+/-_10
154184,abdulma02,Mahmoud Abdul-Rauf,0.107143,1996-11-19,0.364030,SAC,1.0,POR,0.486301,1.0,0.670899,0.464286,0.42,0.357143,0.250000,0.000000,0.000000,0.000000,0.20,0.151515,0.12,0.090909,0.000000,0.142857,0.428571,0.382716,0.457067,0.617391,23.0,1996,abdulma02,1996,0.053571,0.363175,0.6,0.445205,1.0,0.491746,0.196429,0.240,0.071429,0.083333,0.023077,0.017949,0.011111,0.072,0.060606,0.140,0.045455,0.015385,0.142857,0.342857,0.155556,0.249273,0.462609
154185,abdulma02,Mahmoud Abdul-Rauf,0.119048,1996-11-22,0.364339,SAC,0.0,MIA,0.479452,1.0,0.765873,0.321429,0.32,0.214286,0.166667,0.076923,0.076923,0.000000,0.08,0.060606,0.16,0.181818,0.000000,0.214286,0.857143,0.283951,0.352708,0.573913,5.0,1996,abdulma02,1996,0.065476,0.363391,0.5,0.450685,1.0,0.521587,0.203571,0.246,0.085714,0.091667,0.023077,0.020513,0.011111,0.072,0.060606,0.136,0.054545,0.007692,0.150000,0.400000,0.162963,0.250991,0.475652
154186,abdulma02,Mahmoud Abdul-Rauf,0.130952,1996-11-24,0.364545,SAC,1.0,CLE,0.301370,1.0,0.352381,0.071429,0.18,0.000000,0.083333,0.038462,0.025641,0.000000,0.04,0.030303,0.08,0.000000,0.000000,0.071429,0.000000,0.061728,0.157199,0.443478,18.0,1996,abdulma02,1996,0.077381,0.363618,0.5,0.421918,1.0,0.517460,0.207143,0.250,0.085714,0.100000,0.026923,0.023077,0.011111,0.076,0.063636,0.136,0.045455,0.007692,0.157143,0.371429,0.166667,0.252444,0.470435
154187,abdulma02,Mahmoud Abdul-Rauf,0.142857,1996-11-26,0.364751,SAC,1.0,TOR,0.575342,1.0,0.482275,0.178571,0.20,0.071429,0.083333,0.269231,0.205128,0.000000,0.04,0.030303,0.08,0.272727,0.000000,0.000000,0.571429,0.222222,0.361955,0.513043,12.0,1996,abdulma02,1996,0.089286,0.363834,0.6,0.444521,1.0,0.518069,0.196429,0.244,0.092857,0.108333,0.053846,0.041026,0.011111,0.072,0.060606,0.132,0.072727,0.007692,0.135714,0.400000,0.169136,0.261823,0.485217
154188,abdulma02,Mahmoud Abdul-Rauf,0.154762,1996-11-28,0.364957,SAC,1.0,IND,0.376712,1.0,0.480423,0.142857,0.26,0.142857,0.166667,0.076923,0.051282,0.000000,0.12,0.090909,0.12,0.000000,0.000000,0.214286,0.142857,0.148148,0.208719,0.408696,17.0,1996,abdulma02,1996,0.101190,0.364050,0.7,0.434932,1.0,0.512989,0.210714,0.258,0.107143,0.120833,0.061538,0.046154,0.011111,0.080,0.066667,0.116,0.072727,0.007692,0.142857,0.371429,0.183951,0.270145,0.473913
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
904752,zubaciv01,Ivica Zubac,0.750000,2024-04-04,0.339514,LAC,0.0,DEN,0.513699,1.0,0.552646,0.142857,0.22,0.000000,0.000000,0.230769,0.153846,0.055556,0.56,0.454545,0.04,0.090909,0.000000,0.000000,0.571429,0.172840,0.324967,0.460870,12.0,2024,zubaciv01,2024,0.696429,0.338628,0.6,0.484247,1.0,0.439815,0.171429,0.160,0.000000,0.000000,0.096154,0.074359,0.155556,0.268,0.287879,0.056,0.072727,0.107692,0.057143,0.385714,0.149383,0.327741,0.483478
904753,zubaciv01,Ivica Zubac,0.761905,2024-04-05,0.339617,LAC,0.0,UTA,0.698630,1.0,0.380159,0.178571,0.12,0.000000,0.000000,0.076923,0.051282,0.111111,0.32,0.303030,0.08,0.090909,0.230769,0.000000,0.571429,0.148148,0.372523,0.634783,14.0,2024,zubaciv01,2024,0.708333,0.338813,0.6,0.515753,1.0,0.440926,0.185714,0.170,0.000000,0.000000,0.088462,0.069231,0.144444,0.292,0.300000,0.060,0.081818,0.123077,0.050000,0.414286,0.156790,0.338045,0.513913
904754,zubaciv01,Ivica Zubac,0.773810,2024-04-07,0.339823,LAC,0.0,CLE,0.513699,1.0,0.434656,0.250000,0.20,0.000000,0.000000,0.000000,0.000000,0.222222,0.28,0.333333,0.04,0.000000,0.000000,0.214286,0.142857,0.172840,0.313078,0.417391,17.0,2024,zubaciv01,2024,0.720238,0.338999,0.5,0.508219,1.0,0.446376,0.185714,0.172,0.000000,0.000000,0.088462,0.069231,0.144444,0.300,0.306061,0.056,0.045455,0.107692,0.064286,0.400000,0.156790,0.327741,0.494783
904755,zubaciv01,Ivica Zubac,0.785714,2024-04-09,0.340029,LAC,1.0,PHO,0.589041,1.0,0.443386,0.285714,0.26,0.000000,0.000000,0.038462,0.025641,0.111111,0.44,0.393939,0.08,0.000000,0.153846,0.214286,0.000000,0.209877,0.360634,0.652174,10.0,2024,zubaciv01,2024,0.732143,0.339184,0.5,0.511644,1.0,0.462249,0.203571,0.192,0.000000,0.000000,0.092308,0.071795,0.150000,0.316,0.321212,0.064,0.036364,0.115385,0.064286,0.328571,0.170370,0.342272,0.497391
904756,zubaciv01,Ivica Zubac,0.797619,2024-04-12,0.340338,LAC,0.0,UTA,0.493151,1.0,0.163757,0.178571,0.12,0.000000,0.000000,0.000000,0.000000,0.111111,0.00,0.060606,0.00,0.000000,0.076923,0.000000,0.000000,0.123457,0.285337,0.573913,-1.0,2024,zubaciv01,2024,0.744048,0.339380,0.5,0.520548,1.0,0.432275,0.203571,0.186,0.000000,0.000000,0.080769,0.061538,0.144444,0.288,0.296970,0.056,0.036364,0.092308,0.064286,0.328571,0.166667,0.333289,0.500000

In [30]:
removed_columns = list(predictor_df.columns[predictor_df.dtypes == 'object']) + removed_columns + ['Season_10']
removed_columns

['Player ID',
 'Name',
 'Date',
 'Tm',
 'Opp',
 'Player ID_10',
 'Player ID',
 'Date',
 'Name',
 'Tm',
 'Opp',
 'target',
 'Season',
 'Season_10']

In [31]:
selected_columns = predictor_df.columns[~predictor_df.columns.isin(removed_columns)]

In [32]:
sfs = SequentialFeatureSelector(model, n_features_to_select=30, direction='backward', cv=split)
sfs.fit(predictor_df[selected_columns], predictor_df['target'])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          direction='backward', estimator=LinearRegression(),
                          n_features_to_select=30)

In [33]:
predictors = list(selected_columns[sfs.get_support()])
predictors

['G',
 'Age',
 'Result',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FT',
 'ORB',
 'TRB',
 'TOV',
 'PF',
 'Age_10',
 'Away?_10',
 'Result_10',
 'GS_10',
 'MP_10',
 'FG_10',
 '3P_10',
 '3PA_10',
 'FT_10',
 'FTA_10',
 'ORB_10',
 'DRB_10',
 'AST_10',
 'STL_10',
 'BLK_10',
 'TOV_10',
 'PF_10',
 'GmSc_10']

In [34]:
predictions = backtest(predictor_df, model, predictors)

In [35]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

predictions = predictions[predictions['actual'] != -1]

mae = mean_absolute_error(predictions['actual'], predictions['prediction'])
mse = mean_squared_error(predictions['actual'], predictions['prediction'])
rmse = mean_squared_error(predictions['actual'], predictions['prediction'], squared=False)
r2 = r2_score(predictions['actual'], predictions['prediction'])

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R-squared: {r2}")

MAE: 4.435921360917026
MSE: 33.26231918032487
RMSE: 5.767349406818081
R-squared: 0.5099673745274056